name: LDFx
version: 1.2
main: LDFx\ItsToxicGG\LDFx
author: ItsToxicGG
api: 4.0.0

permissions:
  settings.fx:
    description: /settings 
    default: op
  fly.fx:
    description: /fly
    default: op   
  nickcolors.fx:
    description: /nickcolor
    default: op
