name: LDFx
version: 2.0-InDev
main: LDFx\ItsToxicGG\LDFx
author: ItsToxicGG
api: 4.0.0

permissions:
  settings.fx:
    description: /settings 
    default: op
  fly.fx:
    description: /fly
    default: op   
  nickcolor.fx:
    description: /nickcolor
    default: op
