name: LDFx
version: 5.0 # the version im predicting to be when pm5 comes out
main: LDFx\ItsToxicGG\LDFx
author: ItsToxicGG
api: 5.0.0

permissions:
  settings.fx:
    description: /settings 
    default: op
  fly.fx:
    description: /fly
    default: op   
  nickcolor.fx:
    description: /nickcolor
    default: op
