---
# BY ITSTOXICGG
# LDFxConfig V1.0
# BY ITSTOXICGG
# ----------
# The below config allows the plugin to reset flight mode when joining the server
JFlyReset: true

# The below config allows you to send a message to the player when they disable fly
FDMessage: "§cFlyMode is off!"

# The below config enables multi-world settings (OPTIONS: on and off)
FLY-MW: "off"

# List all the worlds that fly would work on!
worlds:
 - "world"
...
