---
# BY ITSTOXICGG
# LDFxConfig V1.0
# BY ITSTOXICGG
# ----------
# Fly-Config
  # The below config allows the plugin to reset flight mode when joining the server
  JFlyReset: true
  # The below config allows you to send a message to the player when they disable fly
  FDMessage: "§cFlyMode is off!"
  # The below config enables multi-world settings (OPTIONS: on and off)
  FLY-MW: "off"
  # List all the worlds that fly would work on!
  worlds:
  - "world"
# EndOfFlyConfig
# Ping-Config
  tps-check: 20

  #Choose the ping of when a player should be kicked, (I recommend you put it above 2000)
  ping-kick: 1000

  #Choose the kick message when a player is kicked for exceeding the ping limit
  kick-message: "§7You were kicked, this was caused by high ping!"
# EndOfPing-Config
# Bow-Config
  enable-sound: true # Enable sound ?
  sound-volume: 1
  sound-pitch: 1
  sound-name: "random.orb"

  enable-message: true # Enable message ?
  hit-message: "§c{name} §7(§aHP: §e{hp}§7)"
 
  enable-popup: false  # Enable popup ?
  hit-popup: "§c{name} §7(§aHP: §e{hp}§7)"

  enable-tip: false  # Enable tip ?
  hit-tip: "§c{name} §7(§aHP: §e{hp}§7)"
# EndOfBow-Config
# AntiVoid-Config
  enabled-worlds: []

  disabled-worlds: []

  use-default-world: false
# EndOfAntiVoid-Config
# NickNames-Config
Random-nicks:
  - ACM
  - Player9920
  - Gamer90
  - Jonatan
  - Jona
  - AbelGod
  - Naruto
  - SIPE
  - CELAR
  - GO3992
#Write here nicknames that you do not like or are risque
#Add the banned nicknames with the following example:
#Not-allow-custom-nicks:
#  - Shit
#  - Fuck
#  - Bitch
Not-allow-custom-nicks:
  - ServerTeam
  - HateYou
  - PocketMine-MP
  - Gay
  - Shit
  - Fuck
  - Bitch
  - Owner
  - Admin
  - "@here"
  - Server
#Forbidden nickname message  
Not-allowed-nick: "§cThis Nick is not allowed."
#Options disable message
Disabled: "§cThis option has been disabled."
#               FORM MESSAGES

#MESSAGES - NICKUI
Nick-Existen: "§l§cSorry!§r§7 But you cannot change your name, because your name is already normal."
Nick-Normal: "§aYour name is now normal."
#Use "{NICK}" to see nickname
Nick-New: "§aYour name is now:§e {NICK}"

#FORM MESSAGE - NICKUI
Nick-Content: "§7Change your nickname discreetly\n§7Your nickname is:§a "
Content-Normal: "§7Change your nickname discreetly\n\n§7You don't have §c§lany§r§7 nickname."

Button-Nick: "§l§3Create a new nickname\n§r§0click to open"
Button-Random: "§l§9Random nickname\n§r§0click to open"
Button-Reset: "§l§4Remove nickname\n§r§0click to open"
#Button-HideNick: "§l§6Hide your name\n§r§0click to open"
Button-Exit: "§c§lEXIT\n§r§0close menu"

Input: "§7Here you can type your custom nickname:"
# EndOfNickNames-Config
# LobbyCore-Config
  #Items 1 | Compass
  item1-name: "§r§cReport Player" # Name Items
  item1-cmd: "report" # Your Commands

  #Items 2 | Name Tag
  item2-name: "§r§aTeleporter" # Name Items
  item2-cmd: "gui" # Your Commands

  #Items 4 | Enchanted Book
  item3-name: "§r§dSocial Menu §7[Use]" # Name Items
  item3-cmd: "socialmenu" # Your Commands
# EndOfLobbyCore-Config
# GameUI-Config
  #GameUI-1
  GameUi-1: "thebridge random"
  
  #GameUI-2
  GameUi-2: "bedwars random"
  
  #GameUI-3
  GameUi-3: "skywars random"
# EndOfGameUI-Config
...
