---
# BY ITSTOXICGG
# LDFxConfig V1.0
# BY ITSTOXICGG
# ----------
# Fly-Config
  # The below config allows the plugin to reset flight mode when joining the server
  JFlyReset: true
  # The below config allows you to send a message to the player when they disable fly
  FDMessage: "§cFlyMode is off!"
  # The below config enables multi-world settings (OPTIONS: on and off)
  FLY-MW: "off"
  # List all the worlds that fly would work on!
  worlds:
  - "world"
# EndOfFlyConfig
# LobbyCore-Config
  #Items 1 | Compass
  item1-name: "§r§cReport Player" # Name Items
  item1-cmd: "report" # Your Commands

  #Items 2 | Name Tag
  item2-name: "§r§aTeleporter" # Name Items
  item2-cmd: "gui" # Your Commands

  #Items 4 | Enchanted Book
  item3-name: "§r§dSocial Menu §7[Use]" # Name Items
  item3-cmd: "socialmenu" # Your Commands
# EndOfLobbyCore-Config
# GameUI-Config
  #GameUI-1
  GameUi-1: "thebridge random"
  
  #GameUI-2
  GameUi-2: "bedwars random"
  
  #GameUI-3
  GameUi-3: "skywars random"
# EndOfGameUI-Config
...
